name: .NET
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "${{ github.workspace }}/docker-compose.yml"
        down-flags: "--volumes"
        services: |
          ea_api
          ea_webapp
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Selenium test
      uses: coactions/setup-xvfb@v1
      with:
        working-directory: ./EaApplicationTest
        run: dotnet test --no-build --verbosity normal
      continue-on-error: true
    - name: Run Specflow Tests
      uses: coactions/setup-xvfb@v1
      with:
        working-directory: ./EaSpecflowTests
        run: dotnet test --no-build --verbosity normal
      continue-on-error: true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: SpecflowReports 
        path: "${{ github.workspace }}/EaSpecflowTests/bin/Debug/net7.0/extentreport.html"
        retention-days: 30
